vich_uploader:
    db_driver: orm

    mappings:
        property_image:
            uri_prefix: uri/img
            upload_destination: '%kernel.project_dir%/public/img'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
